# Generated by Django 3.2.11 on 2022-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0008_auto_20181128_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalipn',
            name='cart_list_ids',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paypalipn',
            name='cart_list_qtys',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
