# Generated by Django 3.2.11 on 2022-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0009_auto_20220112_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalipn',
            name='cart_list_shipping_costs',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='cart_list_ids',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='cart_list_qtys',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
